!=================================================================================================
PROGRAM genCVT_ALP_data


! Description:
! Uses SHTools to generate data needed to do transforms involving associated Legendre polynomials
! (for a particular number of latitude points used by INVICAT)
! Outputs the data in a file (cvt_ass_legendre_poly.dat)
! This file can then be transferred to the computer running INVICAT
!
! Copyright:
!    This software was developed by Ross Bannister, NCEO
!    Copyright 2020, NCEO, All Rights Reserved.
!
! History:
! Version   Date     Comment
! -------   ----     -------
!  1.0      01/2020  Initial version (R.N. Bannister)
!
! Code Description:
!   Language:           Fortran 90.


USE main_data,    ONLY: ylat

USE onedvar_data, ONLY: CVT_HorizCors,         &
                        L,                     &
                        ALPsize,               &
                        SHtools_Normalization, &
                        SHtools_ApplyCSphase,  &
                        SHtools_CRnorm

USE SHTOOLS


IMPLICIT NONE

! Local variables:
INTEGER              :: err, ll, mm, colat, index
REAL                 :: tot

! Allocate the required arrays
ALLOCATE (CVT_HorizCors % assocLegPoly(1:L+1, 1:ALPsize))  ! Associated Legendre polynomials (colat, order)
ALLOCATE (CVT_HorizCors % GaussianCosCoLats(1:L+1))        ! Cosines of the Gaussian co-latitudes
ALLOCATE (CVT_HorizCors % GaussianWts(1:L+1))              ! Gaussian weights
ALLOCATE (CVT_HorizCors % Plm_index(0:L,0:L))              ! For a given l, m this will indicate the index of CVT_assocLegPoly

PRINT *, '=========================================================================================='
PRINT *, 'Program to generate data needed to do transforms involving associated Legendre polynomials'
PRINT *, 'Outputs the data in a file (cvt_ass_legendre_poly.dat)'
PRINT *, 'Transfer this file to the computer running INVICAT'
PRINT *, 'Ross Bannister, NCEO, 2020'
PRINT *, '=========================================================================================='


! Set SHtools data (including associated Legendre polynomials and details about the lats)
CALL SHGLQ (L,                                                 &
            CVT_HorizCors % GaussianCosCoLats(1:L+1),          &
            CVT_HorizCors % GaussianWts(1:L+1),                &
            CVT_HorizCors % assocLegPoly(1:L+1, 1:ALPsize),    &
            SHtools_Normalization,                             &
            SHtools_ApplyCSphase,                              &
            SHtools_CRnorm,                                    &
            err)
PRINT *, 'Exit status from SHGLQ: ', err

! Store mapping from l,m to CVT_assocLegPoly
DO ll = 0, L
  DO mm = 0, L
    IF (mm <= ll) THEN
      CVT_HorizCors % Plm_index(ll,mm) = PlmIndex(ll, mm)
    ELSE
      CVT_HorizCors % Plm_index(ll,mm) = -1
    END IF
  END DO
END DO

! Output data to file
OPEN (13, FILE='cvt_ass_legendre_poly.dat')
WRITE (13,'(A)')   '========================================================='
WRITE (13,'(A)')   'Data file for INCIVAT containing RNB CVT data (B-matrix)'
WRITE (13,'(A)')   'Generated by genCVT_ALP_Data and SHTools library'
WRITE (13,'(AI4)') 'INVICAT ylat          = ', ylat
WRITE (13,'(AI4)') 'L                     = ', L
WRITE (13,'(AI4)') 'SHtools_Normalization = ', SHtools_Normalization
WRITE (13,'(AI4)') 'SHtools_ApplyCSphase  = ', SHtools_ApplyCSphase
WRITE (13,'(AI4)') 'SHtools_CRnorm        = ', SHtools_CRnorm
WRITE (13,'(AI4)') 'ALPsize               = ', ALPsize
WRITE (13,'(A)')   '========================================================='
WRITE (13,'(A)')   'Cosine of Gaussian co-latitudes'
DO colat = 1, L+1
  WRITE (13,*) CVT_HorizCors % GaussianCosCoLats(colat)
END DO
WRITE (13,'(A)') '========================================================='
WRITE (13,'(A)') 'Gaussian weights'
DO colat = 1, L+1
  WRITE (13,*) CVT_HorizCors % GaussianWts(colat)
END DO
WRITE (13,'(A)') '========================================================='
WRITE (13,'(A)') 'Associated Legendre polynomial array mapping'
WRITE (13, *)    CVT_HorizCors % Plm_index(0:L, 0:L)
WRITE (13,'(A)') '========================================================='
WRITE (13,'(A)') 'Associated Legendre polynomials'
DO mm = 0, L
  DO ll = mm, L
    index = CVT_HorizCors % Plm_index(ll,mm)
    WRITE (13,'(AI4AI4)') '*****  m = ', mm, '  l = ', ll
    DO colat = 1, L+1
      WRITE (13,*) CVT_HorizCors % assocLegPoly(colat,index)
    END DO
  END DO
END DO
WRITE (13,'(A)') '========================================================='
WRITE (13,'(A)') 'End of file'
CLOSE (13)

END PROGRAM genCVT_ALP_data
